### ISSUE TITLE
npm install next-postgrest error

### ISSUE THREAD

**Issue by zhuewizz** [zeevo/next-postgrest#1]
npm install next-postgrest error

npm ERR! Cannot read properties of null (reading 'matches')

ubtun 22

**Comment by zeevo** [comment]
Hey there 👋 

I'm not able to recreate this. Can you test with a fresh project using...

1. `npx create-next-app@latest`
2. (in the new project) `npm install next-postgrest`

What version of NodeJS/NPM are you using?

**Comment by zhuewizz** [comment]
tks ,i have slove the programe
